Repository primer/css, pull requests merged in 2018-10, with the labels that each got.

#530 Adding user details to storybook publish script
  script/publish-storybook
Labels: Tag: Bug Fix

#439 Remove primer-page-headers package
  modules/primer-marketing/index.scss
  modules/primer-marketing/package.json
  modules/primer-page-headers/.npmignore
  modules/primer-page-headers/LICENSE
  modules/primer-page-headers/README.md
  modules/primer-page-headers/index.scss
  modules/primer-page-headers/lib/headers.scss
  modules/primer-page-headers/package.json
  modules/primer/package.json
Labels: Tag: Breaking Change, major release

#438 Remove primer-page-sections
  modules/primer-marketing/index.scss
  modules/primer-marketing/package.json
  modules/primer-page-sections/.npmignore
  modules/primer-page-sections/LICENSE
  modules/primer-page-sections/README.md
  modules/primer-page-sections/index.scss
  modules/primer-page-sections/lib/page-section.scss
  modules/primer-page-sections/package.json
  modules/primer/package.json
Labels: Tag: Breaking Change, major release

#440 Remove primer-tables package
  modules/primer-marketing/index.scss
  modules/primer-marketing/package.json
  modules/primer-tables/.npmignore
  modules/primer-tables/LICENSE
  modules/primer-tables/README.md
  modules/primer-tables/index.scss
  modules/primer-tables/lib/tables.scss
  modules/primer-tables/package.json
  modules/primer-tables/stories.js
  modules/primer/package.json
Labels: Tag: Breaking Change, major release

#586 Hiding .Counter component when it's empty.
  modules/primer-labels/README.md
  modules/primer-labels/lib/counters.scss
Labels: Tag: Enhancement, enhancement

#571 Make .container responsive
  modules/primer-layout/lib/container.scss
Labels: Tag: Enhancement, minor release

#570 Bugfix: Make blankslate-narrow responsive
  modules/primer-blankslate/lib/blankslate.scss
Labels: Tag: Enhancement, ds-reviewed, minor release, status: review needed
