Repository primer/css, pull requests merged in 2018-06, with the labels that each got.

#491 Add `backface-visibility` to `.hover-grow`
  modules/primer-utilities/lib/animations.scss
Labels: Tag: Bug Fix, bug, css, status: review needed

#507 Moving the color docs to the style guide
  modules/primer-support/docs/color-system.md
  modules/primer-utilities/docs/colors.md
Labels: Tag: Documentation

#511 change double quotes to single quotes in Avatar stack stories
  modules/primer-avatars/stories.js
Labels: Tag: Polish

#513 Deleting the dev branch workflow instructions
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  script/after_success
  tools/generator-primer-module/README.md
Labels: Tag: Documentation

#515 Auto publish storybook
  script/release
Labels: Tag: Internal

#517 Modifying notify script to publish from each package
  modules/primer-alerts/package.json
  modules/primer-avatars/package.json
  modules/primer-base/package.json
  modules/primer-blankslate/package.json
  modules/primer-box/package.json
  modules/primer-branch-name/package.json
  modules/primer-breadcrumb/package.json
  modules/primer-buttons/package.json
  modules/primer-core/package.json
  modules/primer-forms/package.json
  modules/primer-labels/package.json
  modules/primer-layout/package.json
  modules/primer-markdown/package.json
  modules/primer-marketing-buttons/package.json
  modules/primer-marketing-support/package.json
  modules/primer-marketing-type/package.json
  modules/primer-marketing-utilities/package.json
  modules/primer-marketing/package.json
  modules/primer-navigation/package.json
  modules/primer-page-headers/package.json
  modules/primer-page-sections/package.json
  modules/primer-pagination/package.json
  modules/primer-popover/package.json
  modules/primer-product/package.json
  modules/primer-subhead/package.json
  modules/primer-support/package.json
  modules/primer-table-object/package.json
  modules/primer-tables/package.json
  modules/primer-tooltips/package.json
  modules/primer-truncate/package.json
  modules/primer-utilities/package.json
  modules/primer/package.json
  script/notify
  script/release
  script/release-candidate
  script/release-pr
  tools/generator-primer-module/app/templates/package.json
  tools/primer-module-build/package.json
  tools/stylelint-config-primer/package.json
  tools/stylelint-selector-no-utility/package.json
Labels: Tag: Internal
