Repository primer/css, pull requests merged in 2019-12, with the labels that each got.

#995 Add bold weight to marketing font variables
  src/marketing/support/variables.scss
Labels: Tag: Enhancement, minor release

#998 Use a gray background when hovering SelectMenu items
  docs/content/components/select-menu.md
  src/select-menu/select-menu.scss
Labels: Tag: Bug Fix, minor release

#1000 Update contributing guide for a general audience
  docs/content/getting-started/contributing.md
Labels: Tag: Documentation, patch release

#997 Fix CHANGELOG links
  CHANGELOG.md
Labels: Tag: Internal, patch release

#994 Responsive line-height utilities
  docs/content/utilities/typography.md
  src/utilities/typography.scss
Labels: Tag: Enhancement, minor release

#989 Add link to the Stylelint guide
  docs/content/tools/linting.md
Labels: Tag: Documentation, patch release

#982 Applies .selected styles to [aria-selected=true]
  src/buttons/button-group.scss
  src/buttons/button.scss
  src/navigation/filter-list.scss
  src/navigation/menu.scss
  src/navigation/subnav.scss
  src/support/mixins/buttons.scss
Labels: Tag: Enhancement, minor release
