Repository primer/css, pull requests merged in 2019-11, with the labels that each got.

#966 Rename `.flex-item-equal` to `.flex-1`
  docs/content/utilities/flexbox.md
  src/utilities/flexbox.scss
Labels: Tag: Breaking Change, major release

#974 Add Animated Ellipsis
  docs/content/components/loaders.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  src/loaders/README.md
  src/loaders/index.scss
  src/loaders/loaders.scss
  src/product/index.scss
Labels: Tag: Enhancement, minor release

#978 Add `.css-truncate-overflow`
  docs/content/components/truncate.md
  src/truncate/truncate.scss
Labels: Tag: Enhancement, minor release

#980 Use actual book emoji in Flexbox docs
  docs/content/utilities/flexbox.md
Labels: docs

#981 Autocomplete + Suggester components
  docs/content/components/autocomplete.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  src/autocomplete/README.md
  src/autocomplete/autocomplete.scss
  src/autocomplete/index.scss
  src/autocomplete/suggester.scss
  src/product/index.scss
Labels: Tag: Enhancement, minor release

#979 Add `.radio-group` component
  docs/content/components/forms.md
  src/forms/index.scss
  src/forms/radio-group.scss
Labels: Tag: Enhancement, minor release

#922 More SelectMenu improvements
  deprecations.js
  docs/content/components/select-menu.md
  src/select-menu/select-menu.scss
Labels: Tag: Breaking Change, major release

#987 Add .position-sticky utility
  docs/content/utilities/layout.md
  src/support/variables/layout.scss
Labels: Tag: Enhancement, minor release
