Repository primer/css, pull requests merged in 2019-09, with the labels that each got.

#877 Fix mistake in flex-justify-start explanation
  docs/content/utilities/flexbox.md
Labels: Tag: Documentation, patch release

#862 Import Dropdown component; add dark variants for dropdown and text fields
  docs/content/components/dropdown.md
  docs/content/components/forms.md
  script/bundle-size-report
  src/dropdown/README.md
  src/dropdown/dropdown.scss
  src/dropdown/index.scss
  src/forms/form-control.scss
  src/product/index.scss
Labels: Tag: Enhancement, minor release

#736 Adios purple buttons
  docs/content/components/buttons.md
  src/buttons/button.scss
Labels: Tag: Breaking Change, major release

#662 Removing deprecated column grid styles
  deprecations.js
  docs/content/objects/layout.md
  script/test-deprecations.js
  script/test-doc-urls.js
  src/layout/container.scss
  src/layout/index.scss
Labels: Tag: Breaking Change, major release

#884 Remove .dropdown-menu-content
  deprecations.js
  src/dropdown/dropdown.scss
Labels: Tag: Polish, patch release

#906 Remove "Segoe UI Symbol" from font stack
  src/support/variables/typography.scss
Labels: Tag: Bug Fix, patch release

#903 Move select menu list into the modal div
  docs/content/components/select-menu.md
Labels: Tag: Documentation, patch release

#902 Update "Ship checklist"
  RELEASING.md
Labels: Tag: Internal, patch release

#886 Use inline octicon in branch name example
  docs/content/components/branch-name.md
Labels: Tag: Documentation, patch release

#900 More SelectMenu improvements
  docs/content/components/select-menu.md
  src/select-menu/select-menu.scss
Labels: Tag: Polish, patch release

#916 Add SelectMenu selectors back
  src/select-menu/select-menu.scss
Labels: patch release
