Repository primer/css, pull requests merged in 2019-08, with the labels that each got.

#845 Adding the Header component to primer
  package.json
  pages/css/components/header.md
  src/header/README.md
  src/header/header.scss
  src/header/index.scss
  src/product/index.scss
Labels: Tag: Enhancement, minor release

#869 Switch source order for `styleguide.css`
  docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js
Labels: Tag: Internal, docs

#868 Fix SideNav "jumping" in Safari
  src/navigation/sidenav.scss
Labels: Tag: Bug Fix, bug, patch release

#844 Improve Select Menu spacing
  docs/content/components/select-menu.md
  src/select-menu/select-menu.scss
Labels: patch release

#867 Update Colorable url
  docs/content/utilities/colors.mdx
Labels: patch release

#875 Change order in RELEASING.md
  RELEASING.md
Labels: Tag: Documentation, Tag: Internal

#873 Add default background-color to SideNav
  docs/content/components/navigation.md
  src/navigation/sidenav.scss
Labels: patch release
