Repository primer/css, pull requests merged in 2019-07, with the labels that each got.

#780 Prefer FOUT over FOIT with custom @font-face marketing font
  src/marketing/support/variables.scss
Labels: Tag: Enhancement

#763 Adding flex utilities for grow, order, and width
  pages/css/utilities/flexbox.md
  pages/css/utilities/layout.md
  src/utilities/flexbox.scss
  src/utilities/layout.scss
Labels: Tag: Enhancement, minor release

#812 Improve monospaced font on Chrome Android
  src/support/variables/typography.scss
Labels: enhancement, patch release

#836 BEM multi-word convention for Element or Modifier classes
  pages/css/principles/index.md
Labels: Tag: Documentation, patch release

#831 Toast component
  pages/css/components/toasts.md
  src/product/index.scss
  src/toasts/README.md
  src/toasts/index.scss
  src/toasts/toasts.scss
Labels: minor release, new styles

#808 Select Menu component
  pages/css/components/select-menu-deprecated.md
  pages/css/components/select-menu.md
  src/product/index.scss
  src/select-menu/README.md
  src/select-menu/index.scss
  src/select-menu/select-menu.scss
Labels: minor release, new styles

#827 Side Nav component
  pages/css/components/navigation.md
  src/navigation/index.scss
  src/navigation/sidenav.scss
Labels: minor release, new styles
