Repository primer/css, pull requests merged in 2020-08, with the labels that each got.

#1132 Add .bg-orange to the list of colors
  src/utilities/colors.scss
Labels: Tag: Enhancement, minor release

#1128 Add support for table border
  src/markdown/tables.scss
Labels: Tag: Enhancement, minor release

#1126 Increase border contrast for Label--yellow
  src/labels/labels.scss
Labels: Tag: Polish, patch release

#1122 fix comment typo
  src/progress/progress.scss
Labels: Tag: Documentation, patch release

#1062 Make tabnav responsive
  src/navigation/tabnav.scss
Labels: Tag: Enhancement, minor release

#1121 Update layout when the Counter is empty
  src/labels/counters.scss
Labels: Tag: Polish, minor release
