Repository primer/css, pull requests merged in 2020-09, with the labels that each got.

#1156 Add missing rounded-3 utility
  src/support/variables/misc.scss
  src/utilities/borders.scss
Labels: Tag: Enhancement, minor release

#1157 Overflow responsive variants
  docs/content/utilities/layout.md
  src/utilities/layout.scss
Labels: Tag: Enhancement, minor release

#1152 Remove .autocomplete-results inset border that is occluded by items
  src/autocomplete/autocomplete.scss
Labels: Tag: Polish, patch release

#1155 Place search subnav example on new line
  docs/content/components/navigation.md
Labels: Tag: Documentation, patch release

#1125 Remove reference to Crema
  docs/content/components/alerts.md
Labels: Tag: Documentation, patch release

#1137 Fix CSS error reported by W3C validator
  src/markdown/lists.scss
Labels: Tag: Polish, patch release

#1142 Fix typo in Box documentation
  docs/content/components/box.md
Labels: Tag: Documentation, patch release

#1148 flex wrap reverse added
  docs/content/utilities/flexbox.md
  src/utilities/flexbox.scss
Labels: Tag: Enhancement, minor release

#1147 Increase input font-size on iOS
  src/forms/form-control.scss
Labels: Tag: Polish, patch release

#1165 Replaced old octicons in examples
  docs/content/components/buttons.md
Labels: Tag: Documentation

#1145 Make final position responsive
  docs/content/utilities/layout.md
  src/utilities/layout.scss
Labels: Tag: Enhancement, minor release

#1160 Remove custom emoji from SelectMenu docs
  docs/content/components/select-menu.md
Labels: Tag: Documentation
