Repository primer/css, pull requests merged in 2020-01, with the labels that each got.

#1004 rm deprecated flash-banner component from docs
  docs/content/components/flash-banner.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  script/test-doc-urls.js
Labels: Tag: Documentation, patch release

#1013 Fix docs links
  docs/content/components/box.md
  docs/content/components/progress.md
  docs/content/getting-started/contributing.md
  docs/content/objects/grid.md
  docs/content/principles/index.md
  docs/content/support/breakpoints.md
  docs/content/support/index.md
  docs/content/support/marketing-variables.md
  docs/content/tools/atom-packages.md
  docs/content/tools/linting.md
  docs/content/utilities/box-shadow.md
  docs/content/utilities/flexbox.md
  docs/content/utilities/layout.md
  docs/content/utilities/marketing-borders.md
  docs/content/utilities/marketing-layout.md
  docs/content/utilities/typography.md
Labels: Tag: Documentation

#1012 Improve margin/padding docs
  docs/content/utilities/margin.md
  docs/content/utilities/marketing-margin.md
  docs/content/utilities/marketing-padding.md
  docs/content/utilities/padding.md
Labels: Tag: Documentation

#1001 Add Inter bold font file
  fonts/Inter-Bold.woff
  fonts/Inter-Medium.woff
  fonts/Inter-Regular.woff
Labels: Tag: Enhancement, minor release

#1014 Add aria-disabled state
  docs/content/components/buttons.md
  docs/content/components/loaders.md
  docs/content/components/pagination.md
  docs/content/principles/html.md
  src/buttons/button.scss
  src/marketing/buttons/button.scss
  src/pagination/pagination.scss
  src/support/mixins/buttons.scss
Labels: Tag: Enhancement, minor release

#1005 Add .selected back to the .UnderlineNav
  src/navigation/underline-nav.scss
Labels: Tag: Bug Fix, patch release

#1006 Use ARIA attributes for states
  docs/content/components/breadcrumb.md
  docs/content/components/labels.md
  docs/content/components/navigation.md
  docs/content/components/pagination.md
  src/autocomplete/autocomplete.scss
  src/breadcrumb/breadcrumb.scss
  src/buttons/button-group.scss
  src/buttons/button.scss
  src/navigation/filter-list.scss
  src/navigation/menu.scss
  src/navigation/subnav.scss
  src/navigation/tabnav.scss
  src/navigation/underline-nav.scss
  src/pagination/pagination.scss
  src/support/mixins/buttons.scss
Labels: Tag: Enhancement, minor release

#1002 Fix marketing utilities
  src/marketing/utilities/margin.scss
  src/marketing/utilities/padding.scss
Labels: Tag: Bug Fix, patch release
