Repository primer/css, pull requests merged in 2020-05, with the labels that each got.

#1089 Accessible Progress
  docs/content/components/progress.md
  src/progress/progress.scss
Labels: Tag: Enhancement, minor release

#1075 chore: add missing link to color utilities
  docs/content/components/timeline.md
Labels: Tag: Documentation

#1065 Convert markdown page to one big example
  docs/content/components/markdown.md
Labels: Tag: Documentation, minor release

#1060 Add support for aria-current=false
  src/breadcrumb/breadcrumb.scss
  src/navigation/filter-list.scss
  src/navigation/menu.scss
  src/navigation/sidenav.scss
  src/navigation/subnav.scss
  src/navigation/tabnav.scss
  src/navigation/underline-nav.scss
  src/pagination/pagination.scss
Labels: Tag: Bug Fix, patch release

#1059 Typo in scss.md
  docs/content/principles/scss.md
Labels: Tag: Documentation, minor release
