Repository primer/css, pull requests merged in 2020-03, with the labels that each got.

#1041 Refresh polish ✨
  docs/content/components/avatars.md
  docs/content/components/buttons.md
  docs/content/components/forms.md
  docs/content/components/labels.md
  docs/content/stickersheet/index.md
  docs/content/stickersheet/labels.md
  src/alerts/flash.scss
  src/avatars/avatar.scss
  src/buttons/button.scss
  src/buttons/misc.scss
  src/forms/form-control.scss
  src/forms/form-select.scss
  src/labels/counters.scss
  src/labels/index.scss
  src/labels/issue-labels.scss
  src/labels/labels.scss
  src/labels/mixins.scss
  src/labels/states.scss
  src/navigation/menu.scss
  src/navigation/subnav.scss
  src/support/mixins/typography.scss
  src/support/variables/layout.scss
  src/support/variables/misc.scss
Labels: 🐻 Next

#1049 Fix the closing tag for the buttons
  docs/content/components/select-menu.md
Labels: fr-skip

#1051 Update marketing-type.md
  docs/content/utilities/marketing-type.md
Labels: fr-skip

#1035 Update UnderlineNav-item to not wrap counter & icon
  src/navigation/underline-nav.scss
Labels: Tag: Bug Fix, patch release

#1042 Fix UnderlineNav in Safari
  src/navigation/underline-nav.scss
Labels: Tag: Bug Fix, patch release

#670 Fix Box row top border
  src/box/box.scss
Labels: Tag: Bug Fix, patch release

#1028 Improve .form-group accessibility
  docs/content/components/box.md
  docs/content/components/forms.md
  src/forms/form-control.scss
  src/forms/form-group.scss
  src/forms/form-validation.scss
Labels: Tag: Enhancement, area: accessibility, minor release

#1044 Accessible form validation
  docs/content/components/forms.md
  src/forms/form-group.scss
Labels: Tag: Enhancement, minor release
