Repository primer/css, pull requests merged in 2021-05, with the labels that each got.

#1373 Remove redundant marketing layout selectors
  .changeset/smooth-eagles-tie.md
  deprecations.js
  src/marketing/utilities/layout.scss
Labels: major release

#1372 Merge overlapping marketing spacing utilities into primer core
  .changeset/wild-bottles-tap.md
  deprecations.js
  docs/content/support/marketing-variables.md
  docs/content/support/spacing.md
  docs/content/utilities/margin.md
  docs/content/utilities/marketing-layout.md
  docs/content/utilities/marketing-margin.md
  docs/content/utilities/marketing-padding.md
  docs/content/utilities/padding.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  src/marketing/support/variables.scss
  src/marketing/utilities/index.scss
  src/marketing/utilities/layout.scss
  src/marketing/utilities/margin.scss
  src/marketing/utilities/padding.scss
  src/support/variables/layout.scss
  src/utilities/margin.scss
  src/utilities/padding.scss
Labels: major release

#1379 Add new marketing type scale
  .changeset/nasty-lobsters-lick.md
  deprecations.js
  docs/content/utilities/marketing-type.md
  src/marketing/support/variables.scss
  src/marketing/type/typography.scss
Labels: major release

#1380 Marketing: use size modifiers that don't look like breakpoints modifiers
  .changeset/thirty-experts-exist.md
  deprecations.js
  src/marketing/buttons/button.scss
Labels: major release

#1382 Marketing: optimize body typography inheritance
  .changeset/selfish-moose-suffer.md
  src/marketing/support/variables.scss
  src/marketing/type/typography.scss
Labels: patch release

#1385 Marketing typography: 64px → 68px for third size step
  .changeset/kind-roses-lie.md
  src/marketing/support/variables.scss
Labels: patch release

#1394 Marketing: Fix letter spacing for headers not being correctly overridden at break points
  .changeset/seven-files-guess.md
  src/marketing/type/typography.scss
Labels: patch release

#1391 Improve focus state for .SideNav and .menu
  .changeset/chilly-yaks-hope.md
  src/navigation/menu.scss
  src/navigation/sidenav.scss
Labels: patch release

#1398 Add experimental color variables
  .changeset/cyan-vans-shake.md
  package.json
  src/base/modes-v2.scss
  yarn.lock
Labels: patch release

#1401 Test
  .changeset/proud-rules-wonder.md
  CHANGELOG.md
  README.md
  __tests__/utils/css.js
  package.json
  src/base/modes-v2.scss
  src/marketing/type/typography.scss
  src/navigation/menu.scss
  src/navigation/sidenav.scss
  yarn.lock
Labels: major release

#1403 Marketing: Remove !important from all body content utilities weight declarations
  .changeset/twenty-apples-attack.md
  src/marketing/type/typography.scss
Labels: patch release

#1408 Bump @primer/primitives
  .changeset/olive-forks-breathe.md
  package.json
  src/base/modes-v2.scss
  yarn.lock
Labels: patch release

#1410 Bump @primer/primitives@4.3.4
  .changeset/soft-gifts-pretend.md
  package.json
  yarn.lock
Labels: patch release

#1358 Adding new .Truncate class and deprecating css-truncate
  .changeset/tiny-glasses-battle.md
  deprecations.js
  docs/content/components/truncate.md
  src/truncate/index.scss
  src/truncate/truncate.scss
Labels: minor release

#1415 Bump primer/primitives@4.3.5
  .changeset/hip-chairs-guess.md
  package.json
  yarn.lock
Labels: patch release

#1418 Undeprecate .css-truncate
  .changeset/sixty-drinks-dress.md
  deprecations.js
Labels: patch release

#1424 Update CSS for breadcrumb slash separator
  .changeset/violet-peaches-retire.md
  src/breadcrumb/breadcrumb.scss
Labels: patch release

#1423 Properly calculating the variables computed value for dist folder
  .changeset/fuzzy-cars-promise.md
  package.json
  script/analyze-variables.js
  yarn.lock
Labels: patch release

#992 Support SF Mono font in Firefox and Safari
  .changeset/small-spies-give.md
  src/support/variables/typography.scss
Labels: Tag: Bug Fix, minor release

#1420 lists.scss: reset <ol> without 'type' attr to "decimal"
  .changeset/quiet-rings-confess.md
  src/markdown/lists.scss
Labels: patch release

#1427 Don't require direct version of primitives
  .changeset/hip-bees-look.md
  package.json
  yarn.lock
Labels: patch release

#1422 Improve dividers and allow sidebar positioning when `Layout` is flowing as row.
  .changeset/large-masks-walk.md
  docs/content/components/layout.md
  src/layout/index.scss
  src/layout/layout.scss
  src/layout/mixins.scss
Labels: patch release

#1430 Revert "Support SF Mono font in Firefox and Safari"
  .changeset/long-clouds-retire.md
  src/support/variables/typography.scss
Labels: patch release
