Repository primer/css, pull requests merged in 2021-04, with the labels that each got.

#1294 Link color inherit on :hover
  .changeset/fuzzy-moles-guess.md
  docs/content/components/links.md
  docs/yarn.lock
  src/links/link.scss
Labels: minor release

#1297 Separate active and selected states for `.btn`
  .changeset/kind-lies-check.md
  package.json
  src/buttons/button.scss
  src/buttons/misc.scss
  yarn.lock
Labels: patch release

#1306 Setting min-height on input-sm
  .changeset/twelve-taxis-press.md
  src/forms/form-control.scss
Labels: minor release

#1302 Moving the /fonts/ folder to /src/fonts/
  .changeset/stupid-months-know.md
  src/fonts/Inter-Bold.woff
  src/fonts/Inter-Medium.woff
  src/fonts/Inter-Regular.woff
  src/fonts/LICENSE
Labels: patch release

#1340 Bump @primer/primitives to `4.2.1`
  .changeset/empty-feet-tickle.md
  package.json
  yarn.lock
Labels: patch release

#1350 Bump @primer/primitives
  .changeset/chatty-cherries-tease.md
  package.json
  yarn.lock
Labels: patch release

#1352 Update marketing button styles
  .changeset/tiny-eagles-repair.md
  docs/content/components/marketing-buttons.md
  package.json
  src/marketing/buttons/button.scss
  src/marketing/support/index.scss
  src/marketing/support/mixins.scss
  yarn.lock
Labels: major release

#1339 Changing the browserslist supported browsers to match dotcom.
  .changeset/silly-goats-breathe.md
  package.json
Labels: major release

#1356 Removing primer/octicons dependency and adding octicons styles directly
  .changeset/tiny-mangos-breathe.md
  package.json
  src/base/index.scss
  src/base/octicons.scss
  src/core/index.scss
  yarn.lock
Labels: major release

#1357 typography-base: process 'type' attribute of HTML <ol> tag
  .changeset/odd-foxes-invite.md
  src/markdown/lists.scss
Labels: minor release

#1370 Replace border-overlay with border-primary
  .changeset/khaki-lizards-report.md
  docs/content/support/v16-migration.mdx
  src/autocomplete/autocomplete.scss
  src/autocomplete/suggester.scss
  src/dropdown/dropdown.scss
  src/popover/popover.scss
  src/select-menu/select-menu.scss
  src/utilities/colors.scss
Labels: major release

#1371 Marketing: Deprecate bg-shade-gradient
  .changeset/modern-zebras-press.md
  deprecations.js
  src/marketing/utilities/index.scss
  src/marketing/utilities/misc.scss
Labels: major release

#1369 Marketing: Remove Inter
  .changeset/ninety-lamps-mix.md
  src/fonts/Inter-Bold.woff
  src/fonts/Inter-Medium.woff
  src/fonts/Inter-Regular.woff
  src/fonts/LICENSE
  src/marketing/support/variables.scss
  src/marketing/type/typography.scss
Labels: major release

#1368 Use `--color-icon-secondary` for `.blankslate-icon`
  .changeset/breezy-chairs-cross.md
  src/blankslate/blankslate.scss
Labels: patch release
