Repository primer/css, pull requests merged in 2021-11, with the labels that each got.

#1731 Updating @primer/primitives@6.1.0
  .changeset/gentle-gifts-own.md
  docs/package.json
  docs/yarn.lock
  package.json
  yarn.lock
Labels: patch release

#1738 Update `Layout`'s sidebar width values
  .changeset/clean-books-act.md
  docs/content/components/layout.md
  src/support/variables/layout.scss
Labels: minor release

#1716 Update marketing buttons (including color mode support)
  .changeset/nervous-keys-bow.md
  docs/content/components/marketing-buttons.md
  docs/yarn.lock
  package.json
  src/deprecations.json
  src/marketing/buttons/button.scss
  src/marketing/support/index.scss
  src/marketing/support/mixins.scss
  yarn.lock
Labels: major release

#1746 Remove `Label` bg hack
  .changeset/heavy-rivers-retire.md
  src/labels/labels.scss
Labels: patch release

#1754 Add `Box--overlay` styles + remove styleguide.css from docs
  .changeset/orange-crabs-provide.md
  docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js
  docs/src/color-system.js
  src/box/box-overlay.scss
  src/box/index.scss
Labels: minor release

#1755 Updating primer/primitives@7.1.0 and adding Light High Contrast theme
  .changeset/quiet-spiders-help.md
  docs/.storybook/preview.js
  package.json
  src/color-modes/index.scss
  src/color-modes/themes/light_high_contrast.scss
  yarn.lock
Labels: minor release

#1759 Remove `popover` responsive hack
  .changeset/neat-cheetahs-rescue.md
  docs/content/components/popover.md
  docs/src/stories/components/Popover/Popover.stories.jsx
  docs/src/stories/components/Popover/PopoverFeatures.stories.jsx
  src/popover/popover.scss
Labels: minor release
