Repository primer/css, pull requests merged in 2021-08, with the labels that each got.

#1519 Fix bug where outline was showing up on hover
  .changeset/breezy-ads-eat.md
  src/buttons/misc.scss
Labels: patch release

#1525 render `code` at 100% font size irregardless of direct descension
  .changeset/famous-planes-dress.md
  src/markdown/code.scss
Labels: patch release

#1528 Convert package to a ES module
  .changeset/strong-lemons-ring.md
  .eslintrc.json
  deprecations.js
  package.json
  postcss.config.cjs
  prettier.config.cjs
  script/analyze-variables.js
  script/bundle-size-report.js
  script/dist.js
  script/prepublish
  script/stylelint-todo.cjs
  stylelint.config.cjs
Labels: patch release

#1529 Improve font rendering on Linux
  .changeset/silent-geckos-do.md
  src/support/variables/typography.scss
Labels: minor release

#1540 use standard lifecyle milestones for statuses
  .changeset/neat-laws-matter.md
  docs/content/components/box-overlay.md
  docs/content/components/dropdown.md
  docs/content/components/layout.md
  docs/content/components/links.md
  docs/content/components/loaders.md
  docs/content/components/marketing-buttons.md
  docs/content/components/pagination.md
  docs/content/components/popover.md
  docs/content/components/progress.md
  docs/content/components/select-menu.md
  docs/content/components/timeline.md
  docs/content/components/toasts.md
  docs/content/components/truncate.md
  docs/content/support/color-system.mdx
  docs/content/utilities/colors.mdx
  docs/content/utilities/marketing-type.md
Labels: patch release

#1541 Removing the rem() mixin and usages. Placing the computed values in place.
  .changeset/flat-shirts-lay.md
  src/marketing/buttons/button.scss
  src/marketing/support/mixins.scss
Labels: major release

#1556 Fix TimelineItem--condensed background
  .changeset/silver-items-talk.md
  src/timeline/timeline-item.scss
Labels: patch release

#1555 Add `.wb-break-word` class to existing `.break-word`
  .changeset/healthy-ducks-wave.md
  deprecations.js
  src/utilities/typography.scss
Labels: minor release
