Repository primer/css, pull requests merged in 2021-12, with the labels that each got.

#1805 Fix local dev (revert webpack 5.5.0 → 6.0.0)
  .changeset/long-panthers-provide.md
  docs/package.json
  docs/yarn.lock
Labels: patch release

#1781 Reformat `rgba()` colors
  .changeset/nasty-bananas-drive.md
  src/marketing/buttons/button.scss
Labels: patch release

#1808 Add hover and active states to btn-invisible
  .changeset/shy-vans-draw.md
  src/buttons/misc.scss
Labels: patch release

#1780 ActionList followup
  .changeset/fresh-schools-pull.md
  docs/src/stories/components/ActionList/ActionList.stories.jsx
  docs/src/stories/components/ActionList/ActionListItem.stories.jsx
  docs/src/stories/components/ActionList/ActionListPatterns.stories.jsx
  src/actionlist/action-list-item.scss
  src/actionlist/action-list.scss
Labels: patch release

#1768 Marketing: Add disabled states for buttons (and tweak hover)
  .changeset/orange-camels-heal.md
  src/marketing/buttons/button.scss
Labels: patch release

#1767 Marketing: Remove unused pullquote selector
  .changeset/good-fireants-collect.md
  src/marketing/type/typography.scss
Labels: major release

#1792 Use counter-border for LHC
  .changeset/orange-ties-sin.md
  src/labels/counters.scss
Labels: patch release

#1764 UnderlineNav `:focus` styles
  .changeset/nice-days-jog.md
  docs/src/stories/components/Navigation/UnderlineNav.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavAction.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavItem.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavPatterns.stories.jsx
  src/navigation/underline-nav.scss
  src/support/mixins/misc.scss
Labels: minor release

#1765 Updating and autofixing stylelint
  .github/workflows/ci.yml
  package.json
  src/actionlist/action-list-item.scss
  src/autocomplete/autocomplete.scss
  src/base/base.scss
  src/base/index.scss
  src/blankslate/index.scss
  src/breadcrumb/breadcrumb.scss
  src/buttons/button-group.scss
  src/buttons/button.scss
  src/buttons/misc.scss
  src/color-modes/native.scss
  src/color-modes/themes/dark.scss
  src/color-modes/themes/dark_colorblind.scss
  src/color-modes/themes/dark_dimmed.scss
  src/color-modes/themes/dark_high_contrast.scss
  src/color-modes/themes/light.scss
  src/color-modes/themes/light_colorblind.scss
  src/color-modes/themes/light_high_contrast.scss
  src/forms/form-control.scss
  src/labels/index.scss
  src/labels/labels.scss
  src/layout/index.scss
  src/layout/layout.scss
  src/layout/mixins.scss
  src/markdown/images.scss
  src/marketing/type/typography.scss
  src/navigation/filter-list.scss
  src/navigation/menu.scss
  src/navigation/sidenav.scss
  src/navigation/subnav.scss
  src/navigation/tabnav.scss
  src/navigation/underline-nav.scss
  src/pagination/pagination.scss
  src/select-menu/select-menu.scss
  src/support/mixins/color-modes.scss
  src/support/mixins/typography.scss
  stylelint.config.cjs
  yarn.lock
Labels: minor release

#1821 Underline nav focus state
  .changeset/nice-days-jog.md
  .changeset/orange-ties-sin.md
  docs/src/stories/components/Navigation/UnderlineNav.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavAction.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavItem.stories.jsx
  docs/src/stories/components/Navigation/UnderlineNavPatterns.stories.jsx
  src/labels/counters.scss
  src/navigation/underline-nav.scss
  src/support/mixins/misc.scss
Labels: major release

#1818 [Layout component] Avoid resizing `main` while loading
  .changeset/stale-pugs-eat.md
  src/layout/layout.scss
Labels: patch release

#1827 Support fractional viewport sizes for `max-width` media queries
  .changeset/afraid-jars-occur.md
  .changeset/serious-emus-worry.md
  src/layout/layout.scss
  src/popover/popover.scss
  src/utilities/visibility-display.scss
Labels: patch release

#1803 Actionlist tree-view CSS
  .changeset/healthy-monkeys-complain.md
  docs/.storybook/preview-head.html
  docs/src/stories/components/ActionList/ActionList.stories.jsx
  docs/src/stories/components/ActionList/ActionListItem.stories.jsx
  docs/src/stories/components/ActionList/ActionListItemFeatures.stories.jsx
  docs/src/stories/components/ActionList/ActionListPatterns.stories.jsx
  docs/src/stories/components/ActionList/ActionListTree.stories.jsx
  src/actionlist/action-list-item.scss
  src/actionlist/action-list-tree.scss
  src/actionlist/index.scss
Labels: patch release

#1737 `PageLayout` component / Layout beta + storybook
  .changeset/lemon-games-swim.md
  docs/.storybook/preview-head.html
  docs/.storybook/preview.js
  docs/src/stories/components/ActionList/ActionListExamples.stories.jsx
  docs/src/stories/components/ActionList/ActionListPatterns.stories.jsx
  docs/src/stories/components/Layout/LayoutAlpha.stories.jsx
  docs/src/stories/components/Layout/LayoutBeta.stories.jsx
  docs/src/stories/components/Layout/LayoutExamples.stories.jsx
  docs/src/stories/components/Layout/PageLayout.stories.jsx
  docs/src/stories/components/Layout/SplitPageLayout.stories.jsx
  docs/src/stories/helpers/pageLayoutBehavior.jsx
  src/layout/index.scss
  src/layout/mixins.scss
  src/layout/page-layout.scss
  src/support/variables/layout.scss
Labels: minor release

#1855 Bump primer/primitives to `7.4.0`
  .changeset/beige-hairs-jam.md
  package.json
  yarn.lock
Labels: patch release
