Repository primer/css, pull requests merged in 2021-03, with the labels that each got.

#1238 Move marketing @font-face declarations from vars to type
  src/marketing/support/variables.scss
  src/marketing/type/typography.scss
Labels: Tag: Polish

#1183 Adds flex-shrink: 0 to .avatar class
  src/avatars/avatar.scss
Labels: Tag: Enhancement

#1280 Remove deprecated select menu from nav
  docs/content/components/select-menu.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
Labels: area: documentation, impact: low
