Repository primer/css, pull requests merged in 2021-06, with the labels that each got.

#1432 Layout grid ordering with sidebar placement
  .changeset/smooth-forks-decide.md
  src/layout/layout.scss
  src/layout/mixins.scss
Labels: patch release

#1441 Adding anim-hover-grow to replace hover-grow
  .changeset/grumpy-shrimps-breathe.md
  docs/content/utilities/animations.md
  src/utilities/animations.scss
Labels: minor release

#1448 Replace auto and fade variables
  .changeset/smart-apples-hug.md
  src/base/kbd.scss
  src/blankslate/blankslate.scss
  src/buttons/misc.scss
  src/forms/form-control.scss
  src/navigation/menu.scss
  src/progress/progress.scss
  src/utilities/details.scss
  stylelint.config.js
Labels: patch release

#1450 Adding fill mode forwards to anim-fade-out
  .changeset/neat-poems-flow.md
  src/utilities/animations.scss
Labels: patch release

#1451 Support SF Mono font in Firefox and Safari (take 2)
  .changeset/early-ducks-decide.md
  src/support/variables/typography.scss
Labels: minor release

#1462 Rename and move color mode variables out of base package
  .changeset/mighty-goats-teach.md
  src/base/index.scss
  src/index.scss
  src/support/variables/color-modes-v2.scss
  src/support/variables/color-modes.scss
Labels: major release

#1465 Moving color modes to their own bundle
  .changeset/new-beers-peel.md
  src/color-modes/index.scss
  src/color-modes/themes/dark.scss
  src/color-modes/themes/dark_dimmed.scss
  src/color-modes/themes/light.scss
  src/color-modes/themes/v2/dark.scss
  src/color-modes/themes/v2/dark_dimmed.scss
  src/color-modes/themes/v2/dark_high_contrast.scss
  src/color-modes/themes/v2/light.scss
  src/index.scss
  src/support/variables/color-modes-v2.scss
  src/support/variables/color-modes.scss
Labels: major release

#1472 Use variable for the active border of the UnderlineNav
  .changeset/rude-rockets-flow.md
  src/navigation/underline-nav.scss
Labels: patch release

#1475 Make `TimelineItem-badge--success` ready for V2
  .changeset/silent-cycles-camp.md
  src/timeline/timeline-item.scss
Labels: patch release
