Repository primer/css, pull requests merged in 2021-09, with the labels that each got.

#1563 Revert `TimelineItem-badge` fix
  .changeset/thirty-tips-help.md
  src/timeline/timeline-item.scss
Labels: patch release

#1567 Bump @primer/primitives
  .changeset/late-hounds-scream.md
  .changeset/little-vans-grin.md
  .changeset/many-bananas-design.md
  package.json
  src/base/modes-v2.scss
  src/base/modes.scss
  stylelint.config.cjs
  yarn.lock
Labels: minor release

#1566 Remove break-word from utilities
  .changeset/twelve-fireants-shave.md
  src/utilities/typography.scss
Labels: major release

#1575 Replacing deprecated variables with color v2 variables
  .changeset/cuddly-apricots-protect.md
  src/alerts/flash.scss
  src/autocomplete/autocomplete.scss
  src/autocomplete/suggester.scss
  src/avatars/avatar-parent-child.scss
  src/avatars/avatar-stack.scss
  src/avatars/circle-badge.scss
  src/base/base.scss
  src/base/kbd.scss
  src/base/modes.scss
  src/blankslate/blankslate.scss
  src/box/box.scss
  src/branch-name/branch-name.scss
  src/breadcrumb/breadcrumb.scss
  src/buttons/button.scss
  src/buttons/misc.scss
  src/dropdown/dropdown.scss
  src/forms/form-control.scss
  src/forms/form-group.scss
  src/forms/form-select.scss
  src/forms/form-validation.scss
  src/forms/radio-group.scss
  src/labels/counters.scss
  src/labels/diffstat.scss
  src/labels/labels.scss
  src/labels/states.scss
  src/layout/layout.scss
  src/layout/mixins.scss
  src/links/link.scss
  src/markdown/blob-csv.scss
  src/markdown/code.scss
  src/markdown/headings.scss
  src/markdown/images.scss
  src/markdown/markdown-body.scss
  src/markdown/tables.scss
  src/navigation/filter-list.scss
  src/navigation/menu.scss
  src/navigation/sidenav.scss
  src/navigation/subnav.scss
  src/navigation/tabnav.scss
  src/navigation/underline-nav.scss
  src/pagination/pagination.scss
  src/popover/popover.scss
  src/select-menu/select-menu.scss
  src/subhead/subhead.scss
  src/support/mixins/misc.scss
  src/timeline/timeline-item.scss
  src/toasts/toasts.scss
  src/tooltips/tooltips.scss
  src/utilities/colors.scss
  src/utilities/details.scss
  stylelint.config.cjs
Labels: minor release

#1579 Removing v2 color mode css variable fallbacks
  .changeset/shaggy-shirts-camp.md
  src/forms/form-control.scss
  src/progress/progress.scss
  src/timeline/timeline-item.scss
Labels: minor release

#1581 Updating deprecations.js file to be more straightforward
  .changeset/poor-coins-fix.md
  __tests__/css.test.js
  __tests__/utils/css.js
  deprecations.js
  docs/content/tools/deprecations.md
  package.json
  script/analyze-variables.js
  script/dist.js
  src/deprecations.json
Labels: minor release

#1590 Update Breadcrumbs markup to match w3 aria example
  .changeset/ninety-bags-cover.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/content/components/breadcrumb.md
  src/breadcrumb/breadcrumb.scss
Labels: patch release

#1592 Revert font stack changes
  .changeset/thirty-pants-relate.md
  src/support/variables/typography.scss
Labels: minor release

#1580 Add V2 utilities
  .changeset/dull-birds-protect.md
  src/deprecations.json
  src/utilities/colors.scss
Labels: minor release

#1595 Adding directional margin classes to the utilities
  .changeset/sixty-masks-matter.md
  docs/content/utilities/margin.md
  src/utilities/margin.scss
Labels: minor release

#1594 Loosening the primer/primitives dependency to any minor.patch version
  .changeset/friendly-squids-grin.md
  package.json
  yarn.lock
Labels: patch release

#1596 Added light & dark colorblind themes
  .changeset/afraid-pugs-whisper.md
  package.json
  src/base/modes.scss
  yarn.lock
Labels: minor release

#1599 Prepare main to hold code for next major version
  .changeset/flat-shirts-lay.md
  .changeset/mighty-goats-teach.md
  .changeset/new-beers-peel.md
  .changeset/twelve-fireants-shave.md
  .github/workflows/release.yml
  .github/workflows/release_canary.yml
  .github/workflows/release_candidate.yml
  src/base/index.scss
  src/base/modes.scss
  src/color-modes/index.scss
  src/color-modes/native.scss
  src/color-modes/themes/dark.scss
  src/color-modes/themes/dark_dimmed.scss
  src/color-modes/themes/dark_high_contrast.scss
  src/color-modes/themes/light.scss
  src/index.scss
  src/marketing/buttons/button.scss
  src/marketing/support/mixins.scss
  src/utilities/typography.scss
Labels: major release

#1601 Re-Added light & dark colorblind themes
  .changeset/afraid-pugs-whisper.md
  package.json
  src/color-modes/index.scss
  src/color-modes/themes/dark_protanopia.scss
  src/color-modes/themes/light_protanopia.scss
  yarn.lock
Labels: minor release

#1602 Remove V1 color utilities
  .changeset/nice-terms-juggle.md
  src/utilities/colors.scss
Labels: major release

#1603 Colors V2 docs
  .changeset/small-papayas-prove.md
  docs/content/components/avatars.md
  docs/content/components/box.md
  docs/content/components/buttons.md
  docs/content/components/dropdown.md
  docs/content/components/forms.md
  docs/content/components/labels.md
  docs/content/components/layout.md
  docs/content/components/links.md
  docs/content/components/navigation.md
  docs/content/components/progress.md
  docs/content/components/select-menu.md
  docs/content/components/timeline.md
  docs/content/getting-started/theming.md
  docs/content/objects/grid.md
  docs/content/stickersheet/index.md
  docs/content/stickersheet/labels.md
  docs/content/stickersheet/sizes.md
  docs/content/support/color-system.mdx
  docs/content/support/theming.md
  docs/content/support/v18-migration.mdx
  docs/content/utilities/animations.md
  docs/content/utilities/borders.mdx
  docs/content/utilities/box-shadow.md
  docs/content/utilities/colors.mdx
  docs/content/utilities/flexbox.md
  docs/content/utilities/layout.md
  docs/content/utilities/margin.md
  docs/content/utilities/marketing-layout.md
  docs/content/utilities/padding.md
  docs/content/utilities/typography.md
  docs/src/@primer/gatsby-theme-doctocat/nav.yml
  src/docs.scss
Labels: minor release

#1615 V2 last minute tweaks
  .changeset/healthy-rings-suffer.md
  docs/content/support/v18-migration.mdx
  src/deprecations.json
Labels: major release

#1617 Convert build tools to use dart-sass
  .changeset/olive-ants-kick.md
  .changeset/polite-mayflies-refuse.md
  .node-version
  .nvmrc
  __tests__/build.test.js
  docs/content/support/v18-migration.mdx
  package.json
  postcss.config.cjs
  postcss.config.js
  script/dist.js
  script/primer-css-compiler.js
  src/markdown/markdown-body.scss
  yarn.lock
Labels: major release

#1616 Add footnote styles
  .changeset/gold-games-tickle.md
  docs/content/components/markdown.md
  src/markdown/footnotes.scss
  src/markdown/index.scss
  src/markdown/markdown-body.scss
Labels: minor release

#1626 Changing to @primer/stylelint-config and upgrading @primer/primitives to 5.0 rc
  .changeset/early-insects-share.md
  CHANGELOG.md
  docs/content/tools/linting.md
  package.json
  stylelint.config.cjs
  yarn.lock
Labels: minor release
