Repository primer/css, pull requests merged in 2022-01, with the labels that each got.

#1870 [ActionList] Add hover to `aria-current` elements and other micro interactions
  .changeset/six-avocados-promise.md
  src/actionlist/action-list-item.scss
Labels: patch release

#1856 ActionList item outlines for high contrast theme
  .changeset/few-mice-scream.md
  src/actionlist/action-list-item.scss
Labels: patch release

#1893 Storybook: Examples as the last item
  docs/.storybook/preview.js
Labels: storybook

#1894 Make `pagination` responsive by default
  .changeset/swift-actors-drum.md
  src/pagination/pagination.scss
Labels: patch release

#1890 Add 2 color definitions for Windows High Contrast mode
  .changeset/seven-dolls-explain.md
  src/color-modes/native.scss
Labels: patch release

#1876 Add mono font stack to <samp> tag
  .changeset/nice-beers-peel.md
  docs/content/components/markdown.md
  src/base/normalize.scss
  src/base/typography-base.scss
  src/markdown/code.scss
Labels: minor release
