Repository primer/css, pull requests merged in 2022-04, with the labels that each got.

#1997 Add Tritanopia theme
  .changeset/healthy-zoos-play.md
  docs/src/stories/playground/ColorPlayground.stories.jsx
  docs/src/stories/playground/Playground.stories.jsx
  package.json
  src/color-modes/index.scss
  src/color-modes/themes/dark_tritanopia.scss
  src/color-modes/themes/light_tritanopia.scss
  yarn.lock
Labels: minor release

#2002 Always break long `branch-name`s
  .changeset/early-spoons-greet.md
  src/branch-name/branch-name.scss
Labels: patch release

#1996 TreeView: remove bold active items + markup changes
  .changeset/curvy-ways-taste.md
  src/actionlist/action-list-tree.scss
Labels: patch release

#2019 [Bug] TreeView animation and padding fix
  .changeset/fuzzy-pants-decide.md
  docs/src/stories/ui-patterns/ActionList/ActionListItem.stories.jsx
  docs/src/stories/ui-patterns/ActionList/ActionListItemCollapsible.stories.jsx
  docs/src/stories/ui-patterns/ActionList/ActionListTree.stories.jsx
  docs/src/stories/ui-patterns/ActionList/TreeViewListItemCollapsible.stories.jsx
  docs/src/stories/ui-patterns/ActionList/TreeViewReadMe.stories.mdx
  src/actionlist/action-list-tree.scss
Labels: patch release

#2030 Fix `hasPane` default value for Layout stories
  docs/src/stories/components/Layout/LayoutBeta.stories.jsx
  docs/src/stories/components/Layout/SplitPageLayout.stories.jsx
Labels: storybook

#2041 Upgrading to stylelint-config-12.4.0
  .changeset/tame-clouds-shop.md
  package.json
  src/box/box-overlay.scss
  src/forms/form-group.scss
  src/marketing/type/typography.scss
  src/marketing/utilities/layout.scss
  src/navigation/subnav.scss
  src/popover/popover.scss
  src/support/mixins/color-modes.scss
  src/support/mixins/layout.scss
  src/support/variables/layout.scss
  src/timeline/timeline-item.scss
  yarn.lock
Labels: patch release

#2046 Global focus style CSS from feature flag
  .changeset/young-trainers-yell.md
  src/autocomplete/autocomplete.scss
  src/forms/form-validation.scss
Labels: major release

#2047 UnderlineNav bug fix
  .changeset/ninety-bobcats-do.md
  src/navigation/underline-nav.scss
Labels: major release

#2049 Comment box upload focus border-radius
  .changeset/beige-horses-fetch.md
  src/forms/form-validation.scss
Labels: major release

#2048 Fix headings with an anchor in a summary
  .changeset/hip-readers-press.md
  src/markdown/headings.scss
Labels: patch release
