Repository primer/css, pull requests merged in 2023-11, with the labels that each got.

#2548 Sync docs/package.json and docs/package-lock.json
  docs/package-lock.json
Labels: skip changeset

#2549 add more backdrop selectors to properly inherit theme colors
  .changeset/popular-hounds-sin.md
  src/support/mixins/color-modes.scss
Labels: patch release

#2554 Remove primitives css tokens import from support package
  .changeset/gorgeous-jeans-camp.md
  src/support/index.scss
Labels: minor release
