Repository primer/css, pull requests merged in 2024-03, with the labels that each got.

#2586 upgrade all deps
  .github/workflows/axe.yml
  .github/workflows/codeql.yml
  .github/workflows/stale.yml
  package-lock.json
  package.json
Labels: skip changeset

#2581 Update shadow utils
  .changeset/dry-schools-clap.md
  src/select-menu/select-menu.scss
  src/toasts/toasts.scss
  src/utilities/box-shadow.scss
Labels: patch release

#2588 Bump Primitives + fix selectmenu
  .changeset/ninety-baboons-compete.md
  package-lock.json
  package.json
  src/select-menu/select-menu.scss
Labels: patch release

#2590 Update legacy shadows
  .changeset/angry-cycles-smell.md
  src/select-menu/select-menu.scss
  src/toasts/toasts.scss
Labels: patch release

#2593 Update bg-color utility docs to say `muted`
  docs/stories/utilities/Color.stories.jsx
Labels: skip changeset

#2598 Remove marketing variables
  .changeset/angry-toys-live.md
  src/marketing/support/variables.scss
Labels: minor release

#2596 Move native color styles from the color-modes bundle to the base bundle
  .changeset/fair-cups-lay.md
  src/base/index.scss
  src/base/native-colors.scss
  src/color-modes/index.scss
Labels: minor release
